---
name: test-playbook

on:
  push:
    branches:
      - main

jobs:
  run_playbook:
    uses: ./.github/workflows/sync.yml
    secrets: inherit
    with:
      environment: DEVINT
      secret_id: PASSWORD
