name: Update Email Address

on:
  push:
    branches:
      - main

jobs:
  update_email:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      env:
        USERNAME: username
        PASSWORD: password
      run: |
        $User = "Dan Jump"
        $EmailAddress = "dan.jump@northamerica.contoso.com"
        $Username = $env:USERNAME
        $Password = $env:PASSWORD

        $SecurePassword = ConvertTo-SecureString -String $Password -AsPlainText -Force
        $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $Username, $SecurePassword

        $Params = @{
          Identity = $User
          EmailAddresses = @{ add = $EmailAddress }
          Credential = $Credential
        }

        Set-Mailbox @Params
name: Update Email Address

on:
  push:
    branches:
      - main

jobs:
  update_email:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
 
      run: |
          echo hello
