name: Update Email Address

on:
  push:
    branches:
      - main

jobs:
  update_email:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run PowerShell script

      run: |
        $User = "Dan Jump"
        $EmailAddress = "dan.jump@northamerica.contoso.com"
        $Username = $env:USERNAME
        $Password = $env:PASSWORD

         
        $Credential = New-Object -TypeName System.Management.Automation.PSCredential 

        $Params = @{
          Identity = $User
          EmailAddresses = @{ add = $EmailAddress }
          Credential = $Credential
        }

        Set-Mailbox @Params
