name: Run PowerShell

on:
  push:
    branches:
      - main

jobs:
  run_powershell:
    runs-on: windows-latest
    steps:
      - name: Run PowerShell commands
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          $username = $env:USERNAME
          $password = $env:PASSWORD
          
          # PowerShell script using provided credentials
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)
          
          # Your AD command here
          $aduser = Get-ADUser -Identity aws_blah -Credential $credential

          # Further actions or output handling
